mpo_500_omni_wheel_front_left_controller:
    type: velocity_controllers/JointVelocityController
    joint: mpo_500_omni_wheel_front_left_joint
    # pid: {p: 100.0, i: 0.01, d: 10.0}

mpo_500_omni_wheel_front_right_controller:
    type: velocity_controllers/JointVelocityController
    joint: mpo_500_omni_wheel_front_right_joint
    # pid: {p: 100.0, i: 0.01, d: 10.0}

mpo_500_omni_wheel_back_left_controller:
    type: velocity_controllers/JointVelocityController
    joint: mpo_500_omni_wheel_back_left_joint
    # pid: {p: 100.0, i: 0.01, d: 10.0}

mpo_500_omni_wheel_back_right_controller:
    type: velocity_controllers/JointVelocityController
    joint: mpo_500_omni_wheel_back_right_joint
    # pid: {p: 100.0, i: 0.01, d: 10.0}